name: Run Docker container
description: Executes a command while running a Docker container
inputs:
  command:
    description: Command to execute
    required: true
  container-port:
    default: ""
    description: Container port to expose, defaults to `port`
    required: false
  env:
    description: Environment variables to set in the container (newline-delimited string)
    required: false
  host:
    default: "false"
    description: Whether to run the container in host network mode
    required: false
  image:
    description: Docker image to test
    required: true
  port:
    default: "8080"
    description: The port in which the app is served on
    required: false
  registry:
    description: URL of the registry of the Docker container
    required: false
  registry-user:
    description: Username for the registry
    required: false
  registry-password:
    description: Password for the registry
    required: false
runs:
  using: composite
  steps:
    - name: Authenticate to registry
      if: ${{ (inputs.registry && inputs.registry-user && inputs.registry-password) || inputs.registry == 'ghcr.io' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry-user && inputs.registry-user || (inputs.registry == 'ghcr.io' && github.actor || '') }}
        password: ${{ inputs.registry-password && inputs.registry-password || (inputs.registry == 'ghcr.io' && github.token || '') }}
    - name: Run container
      shell: bash
      env:
        CONTAINER_PORT: ${{ inputs.container-port }}
      run: |
        ENV_FLAGS=""
        while IFS= read -r line; do
          [[ -z "$line" ]] && continue
          ENV_FLAGS="$ENV_FLAGS -e $line"
        done <<< "${{ inputs.env }}"

        docker run -d $ENV_FLAGS \
          --name=container \
          -p ${{ inputs.port }}:${CONTAINER_PORT:-${{ inputs.port }}} \
          ${{ inputs.host == 'true' && '--network host' || '' }} \
          ${{ inputs.image }}
    - name: Execute command
      shell: bash
      run: ${{ inputs.command }}
    - name: Stop container
      shell: bash
      run: docker stop container && docker rm container
