# GitHub reusable workflow for building, testing and pushing a container image
# to a Docker registry.

on:
  workflow_call:
    inputs:
      artifacts-name:
        default: build-artifacts
        description: Artifacts name
        type: string
      artifacts-path:
        description: Artifacts path (relative to working directory)
        required: false
        type: string
      build-args:
        description: List of build-time variables
        required: false
        type: string
      build-secrets:
        description: List of build-time secrets
        required: false
        type: string
      push:
        default: false
        description: Specifies if pushing image to registry
        type: boolean
      image-name:
        default: ${{ github.repository }}
        description: Docker image base name
        type: string
      image-tag-suffix:
        description: Docker image tag suffix
        required: false
        type: string
      registry:
        default: hub.docker.com
        description: Registry path (required if `push` is `true`)
        type: string
      test-command:
        description: Command for running tests
        type: string
    outputs:
      artifacts-name:
        description: Name of the uploaded artifacts
        value: ${{ jobs.build.outputs.artifacts-name }}
      artifacts-path:
        description: Path of the uploaded artifacts (relative to working directory)
        value: ${{ jobs.build.outputs.artifacts-path }}
      image:
        description: The built Docker image
        value: ${{ jobs.build.outputs.image }}
    secrets:
      github-token:
        description: GitHub personal access token to use when checking out private repositories
        required: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      artifacts-name: ${{ inputs.artifacts-path && inputs.artifacts-name || '' }}
      artifacts-path: ${{ inputs.artifacts-path }}
      image: ${{ inputs.push && fromJSON(steps.metadata.outputs.json).tags[0] || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.github-token && secrets.github-token || github.token }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build test target
        id: build-test
        if: ${{ inputs.test-command }}
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          context: .
          load: true
          secrets: |
            ${{ secrets.github-token && format('GITHUB_TOKEN={0}', secrets.github-token) || '' }}
            ${{ inputs.build-secrets }}
          tags: ${{ inputs.image-name }}:test
          target: test
      - name: Run tests
        if: ${{ inputs.test-command }}
        run: IMAGE=${{ fromJSON(steps.build-test.outputs.metadata)['image.name'] }} ${{ inputs.test-command }}
      - name: Build prod target
        id: build-prod
        uses: docker/build-push-action@v5
        with:
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          context: .
          load: true
          secrets: |
            ${{ secrets.github-token && format('GITHUB_TOKEN={0}', secrets.github-token) || '' }}
            ${{ inputs.build-secrets }}
          tags: ${{ inputs.image-name }}:prod
          target: prod
      - name: Set up release metadata
        if: ${{ inputs.push }}
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ format('{0}/', inputs.registry) || '' }}${{ inputs.image-name }}
          tags: |
            type=ref,event=pr,suffix=${{ inputs.image-tag-suffix }}
            type=semver,pattern={{version}},suffix=${{ inputs.image-tag-suffix }}
            type=sha,prefix=,format=short,priority=1000,suffix=${{ inputs.image-tag-suffix }}
            type=raw,value=latest,suffix=${{ inputs.image-tag-suffix }}
      - name: Push image release to registry
        uses: docker/build-push-action@v5
        if: ${{ inputs.push }}
        with:
          build-args: ${{ inputs.build-args }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          context: .
          labels: ${{ steps.metadata.outputs.labels }}
          provenance: false
          push: true
          secrets: |
            ${{ secrets.github-token && format('GITHUB_TOKEN={0}', secrets.github-token) || '' }}
            ${{ inputs.build-secrets }}
          tags: ${{ steps.metadata.outputs.tags }}
      - name: Copy artifacts
        if: ${{ inputs.artifacts-path }}
        env:
          IMAGE: ${{ fromJSON(steps.build-prod.outputs.metadata)['image.name'] }}
        run: |-
          from_path="/var/app/${{ inputs.artifacts-path }}"
          to_path="${PWD}/${{ inputs.artifacts-path }}"
          process_name="tmp"

          echo "Copying files from ${IMAGE}... from=${from_path}, to=${to_path}"

          mkdir -p $to_path
          docker run -td --rm --name $process_name $IMAGE
          docker cp $process_name:$from_path $to_path
          docker stop $process_name

          echo "Copying files from ${IMAGE}... OK"
      - name: Upload artifacts
        if: ${{ inputs.artifacts-path }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifacts-name }}
          path: ${{ inputs.artifacts-path }}
      - name: Append summary
        if: ${{ inputs.push }}
        run: |-
          image=${{ fromJSON(steps.metadata.outputs.json).tags[0] }}
          echo "Pushed image [\`${image}\`](https://${image}) to registry \`${{ inputs.registry }}\`." >> $GITHUB_STEP_SUMMARY
