on:
  workflow_call:
    inputs:
      artifacts-name:
        default: build-artifacts
        description: Artifacts name
        type: string
      artifacts-path:
        description: Artifacts path (relative to working directory)
        required: false
        type: string
      build-command:
        default: npm run build
        description: Build command
        type: string
      service-image:
        description: Image of the service to use
        required: false
        type: string
      service-port:
        default: 8080:8080
        description: Port mapping of the service (i.e. <host_port>:<service_container_port>)
        type: string
      skip-tests:
        default: false
        description: Specifies if tests should run
        type: boolean
      test-command:
        default: npm test
        description: Command for running tests
        type: string
    outputs:
      artifacts-name:
        description: Name of the uploaded artifacts
        value: ${{ jobs.build.outputs.artifacts-name }}
      artifacts-path:
        description: Path of the uploaded artifacts (relative to working directory)
        value: ${{ jobs.build.outputs.artifacts-path }}
    secrets:
      gh-access-token:
        description: GitHub access token for checking out private repos
        required: false
jobs:
  build:
    name: Node
    runs-on: ubuntu-latest
    services:
      service:
        image: ${{ inputs.service-image }}
        ports:
          - ${{ inputs.service-port }}
    outputs:
      artifacts-name: ${{ inputs.artifacts-path && inputs.artifacts-name || '' }}
      artifacts-path: ${{ inputs.artifacts-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.gh-access-token && secrets.gh-access-token || github.token }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-npm-cache-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Node modules
        run: npm install
      - name: Build
        run: ${{ inputs.build-command }}
      - name: Store artifacts
        if: ${{ inputs.artifacts-path }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifacts-name }}
          path: ${{ inputs.artifacts-path }}
      - name: Test
        if: ${{ !inputs.skip-tests }}
        run: ${{ inputs.test-command }}
