on:
  workflow_call:
    inputs:
      artifacts-name:
        default: build-artifacts
        description: Name of the artifacts to download
        type: string
      artifacts-path:
        description: Path (relative to working directory) to download artifacts to
        required: false
        type: string
      create-release:
        default: false
        description: Specifies if a release should be created
        type: boolean
      registry:
        default: https://registry.npmjs.org
        description: NPM package registry URL
        type: string
      run-command:
        description: Command to run before deploying
        required: false
        type: string
    secrets:
      gh-access-token:
        description: GitHub access token for checking out private repos
        required: false
      npm-auth-token:
        description: NPM auth token
        required: false
jobs:
  deploy:
    name: NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.gh-access-token && secrets.gh-access-token || github.token }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          registry-url: ${{ inputs.registry }}
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-npm-cache-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Node modules
        run: npm install
      - name: Download artifacts
        if: ${{ inputs.artifacts-path }}
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts-name }}
          path: ${{ inputs.artifacts-path }}
      - name: Run
        if : ${{ inputs.run-command }}
        run: ${{ inputs.run-command }}
      - name: Create release
        if: ${{ inputs.create-release }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            const tag = process.env.GITHUB_REF.split('/').slice(-1)[0]

            try {
              await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: tag,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: tag,
              })
            }
            catch (error) {
              core.setFailed(error.message)
            }
      - name: Deploy to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-auth-token && secrets.npm-auth-token || github.token }}
        run: |-
          if npm publish; then
            echo "Successfully published version \`$(npm pkg get version | sed 's/"//g')\`to NPM registry \`${{ inputs.registry }}\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "Failed to publish to NPM registry \`${{ inputs.registry }}\`" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi